url: 
baseurl: 

# Site settings
title: Restaurante "Mikrokosmos"
email: emma.zambranoesp@ug.edu.ec
description: "Restaurante Familiar"


# Team names, titles and social links
people:
- name: Emma Zambrano
  pic:
  position: Lead Designer and developed
  social:
    - title: Gmail
      url: # emma.zambranoesp@ug.edu.ec
    - title: instagram
      url: #
    - title: github
      url: # https://github.com/EmmaZambrano

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/emma-zambrano-19177a192/
  - title: pinterest
    url: www.pinterest.com/emmazambrano40
  
# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
